//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Networx.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Review
    {
        public int Review_ID { get; set; }
        [Required(ErrorMessage = "Please enter a game")]
        //Prevents sql injection through tautology
        [RegularExpression("@^[^=]&", ErrorMessage = "cannot put equals in this form")]
        public int Game_id { get; set; }
        public int User_id { get; set; }
        [Required(ErrorMessage = "Please enter the text for the review")]
        //Prevents sql injection through tautology
        [RegularExpression("@^[^=]&", ErrorMessage = "cannot put equals in this form")]
        public string Review_text { get; set; }
        [Required(ErrorMessage = "Please enter a review score")]
        //Prevents sql injection through tautology
        [RegularExpression("@^[^=]&", ErrorMessage = "cannot put equals in this form")]
        public int Review_score { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}
