//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Networx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Review_ID { get; set; }
        public int Game_id { get; set; }
        public int User_id { get; set; }
        public string Review_text { get; set; }
        public int Review_score { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}
