//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Networx.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public int User_ID { get; set; }
        [Required(ErrorMessage = "Please enter your username")]
        //Prevents sql injection through tautology
        [RegularExpression("@^[^=]&", ErrorMessage = "cannot put equals in this form")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Please enter your password")]
        //Prevents sql injection through tautology
        [RegularExpression ("@^[^=]&",ErrorMessage ="cannot put equals in this form")]
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
